// Compiles design/tokens.json (a copy of the design system's tokens) into src/styles/tokens.css.
import { readFileSync, writeFileSync } from "node:fs";

const tokens = JSON.parse(readFileSync(new URL("../design/tokens.json", import.meta.url), "utf8"));
const themes = tokens.color.themes.map((theme) => theme.id);
const [first, ...rest] = themes;

const resolve = (token, theme) => {
  const raw = typeof token.value === "string" ? token.value : (token.value[theme] ?? token.value[first]);
  const alias = /^\{(.+)\}$/.exec(raw);
  return alias ? `var(--${alias[1]})` : raw;
};
const block = (selector, lines) => `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}\n`;

const themed = [...tokens.color.tokens, ...tokens.shadow.tokens];
const flat = ["spacing", "radius", "motion", "layout"].flatMap((family) => tokens[family].tokens);

let css = "/* Generated by scripts/build-tokens.mjs from design/tokens.json. Do not edit. */\n\n";
css += block(`:root, [data-theme="${first}"]`, [
  `color-scheme: ${first};`,
  ...themed.map((token) => `--${token.name}: ${resolve(token, first)};`),
]);
for (const theme of rest) {
  css += "\n" + block(`[data-theme="${theme}"]`, [
    `color-scheme: ${theme};`,
    ...themed.map((token) => `--${token.name}: ${resolve(token, theme)};`),
  ]);
}
css += "\n" + block(":root", flat.map((token) => `--${token.name}: ${token.value};`));

writeFileSync(new URL("../src/styles/tokens.css", import.meta.url), css);
console.log(`tokens.css: ${themed.length} themed, ${flat.length} flat`);
